### ISSUE TITLE
Fix telemetry to not stop deployments because location is not exists

### ISSUE THREAD

**Issue by jrspinella** [Azure/NoOpsAccelerator#184] opened 2022-10-27 22:25 UTC
**Describe the bug**
If a PID exists in a region, it stops the deployment and gives this error rbecause location is not exists:

 {"code": "InvalidDeployment", "message": "The 'location' property must be specified for 'pid-66764817-8a40-4c5a-a9ea-dee657961d13-ccggon4scv3xw'. Please see https://aka.ms/deploy-to-subscription for usage details."}.

**To Reproduce**

1. Run platform hub/3 spoke
2. See the error

**Expected behavior**
Deployment is supposed to work without this error

**Software versions used:**

- Azure CLI version [v2.23.0]
- Azure Bicep version [v0.6.8]

**Comment by jftl6y** [comment] 2022-11-11 21:34
Duplicate of #124

**Closed by jftl6y** 2022-11-11 21:34 UTC
Labels: bug, bicep, core, platforms, workloads
